# Form implementation generated from reading ui file 'addDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Entry import Entry
from datetime import date


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 440, 401, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 441, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 30, 0)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(date.today())
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.textEdit = QtWidgets.QPlainTextEdit(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)

        self.lineEdit.setMaxLength(30)
        self.lineEdit_3.setMaxLength(30)
        self.lineEdit_4.setMaxLength(10)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nazwa"))
        self.label_2.setText(_translate("Dialog", "Data"))
        self.label_3.setText(_translate("Dialog", "Kategoria"))
        self.label_4.setText(_translate("Dialog", "Cena"))
        self.label_5.setText(_translate("Dialog", "Opis"))

    def returnData(self):
        return (self.lineEdit.text(), self.dateEdit.date().toPyDate(), self.lineEdit_3.text(), float(self.lineEdit_4.text()), self.textEdit.toPlainText())

    def checkIfDataIsCorrect(self, mainWindow):
        errorDialog = QtWidgets.QErrorMessage(mainWindow)
        try:
            if not self.lineEdit.text().isalnum():
                errorDialog.showMessage('Nazwa płatności jest niepoprawna, powinna ona zawierać tylko znaki alfanumeryczne {[a-z][0-9]} oraz spacje')
                return False
            elif not self.lineEdit_3.text().isalnum():
                errorDialog.showMessage('Nazwa kategorii jest niepoprawna, powinna ona zawierać tylko znaki alfanumeryczne {[a-z][0-9]} oraz spacje')
                return False
            elif not 0.0 <= float(self.lineEdit_4.text()) <= 10 ** 7:
                errorDialog.showMessage('Cena jest niepoprawna, powinna być liczbą zmiennoprzecinkową o znaku rozdzielającym część dziesiętną i całkowitą {.}')
                return False
            else:
                return True
        except Exception:
            errorDialog.showMessage(
                'Cena jest niepoprawna, powinna być liczbą zmiennoprzecinkową o znaku rozdzielającym część dziesiętną i całkowitą {.}')
            return False

    def setupDialog(self, entry):
        self.lineEdit.setText(entry.name)
        self.dateEdit.setDate(entry.date)
        self.lineEdit_3.setText(entry.category)
        self.lineEdit_4.setText(str(entry.cost))
        self.textEdit.setPlainText(entry.description)
    def editElement(self, entry):
        if(self.lineEdit.text() != entry.name):
            entry.name = self.lineEdit.text()
        if(self.dateEdit.date().toPyDate() != entry.date):
            entry.date = self.dateEdit.date().toPyDate()
        if (self.lineEdit_3.text() != entry.category):
            entry.category = self.lineEdit_3.text()
        if (float(self.lineEdit_4.text()) != entry.cost):
            entry.cost = float(self.lineEdit_4.text())
        if (self.textEdit.toPlainText() != entry.description):
            entry.description = self.textEdit.toPlainText()

    def readOnlyDialog(self):
        self.lineEdit.setReadOnly(True)
        self.dateEdit.setReadOnly(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4.setReadOnly(True)
        self.textEdit.setReadOnly(True)

def runAndReturnAddWindow(mainWindow):
    Dialog = QtWidgets.QDialog(mainWindow)
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    if Dialog.exec():
        if ui.checkIfDataIsCorrect(mainWindow):
            return ui.returnData()
        return None
    return None

def runAndReturnEditWindow(mainWindow, uiMainWindow):
    entryToEdit = uiMainWindow.appLogicInstance.getAllPaymentsEntryList().getInsideEntryList()[uiMainWindow.allPaymentsList.row(uiMainWindow.allPaymentsList.currentItem())]
    Dialog = QtWidgets.QDialog(mainWindow)
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.setupDialog(entryToEdit)
    if Dialog.exec():
        if ui.checkIfDataIsCorrect(mainWindow):
            ui.editElement(entryToEdit)
            print(entryToEdit)
            uiMainWindow.updateAllTabs()
def runReadOnly(mainWindow, entryList, listWidget):
        entryToRead = entryList.getInsideEntryList()[
            listWidget.row(listWidget.currentItem())]
        Dialog = QtWidgets.QDialog(mainWindow)
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        ui.setupDialog(entryToRead)
        ui.readOnlyDialog()
        Dialog.exec()