import traceback

from PyQt6 import QtCore, QtGui, QtWidgets

import addDialog
from AppLogic import *
import actionMethods as am
import calendarMethods as cm
import daySummaryMethods as dsm
import allPaymentsMethods as apm
import weekMethods as wm
import qdarktheme
class Ui_MainWindow(object):

    def __init__(self):
        super().__init__()
        self.appLogicInstance = AppLogic()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(900, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(900, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 56, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 42, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 900, 900))
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 900))
        self.tabWidget.setMaximumSize(QtCore.QSize(900, 900))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.CalendarTab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.CalendarTab.setPalette(palette)
        self.CalendarTab.setObjectName("CalendarTab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.CalendarTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 831))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.gridLayoutWidget)
        self.calendar.setEnabled(True)
        self.calendar.setMinimumSize(QtCore.QSize(0, 450))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.NoRole, brush)
        self.calendar.setPalette(palette)
        self.calendar.setMinimumDate(QtCore.QDate(1752, 9, 17))
        self.calendar.setGridVisible(False)
        self.calendar.setObjectName("calendar")
        self.gridLayout.addWidget(self.calendar, 0, 0, 1, 1)
        self.calendarRecordsList = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calendarRecordsList.setFont(font)
        self.calendarRecordsList.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.calendarRecordsList.setObjectName("calendarRecordsList")
        self.gridLayout.addWidget(self.calendarRecordsList, 2, 0, 1, 1)
        self.tabWidget.addTab(self.CalendarTab, "")
        self.weekTab = QtWidgets.QWidget()
        self.weekTab.setObjectName("weekTab")
        self.epicLabel = QtWidgets.QLabel(parent=self.weekTab)
        self.epicLabel.setGeometry(QtCore.QRect(260, 40, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.epicLabel.setFont(font)
        self.epicLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.epicLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.epicLabel.setObjectName("epicLabel")
        self.generatePlotButton = QtWidgets.QPushButton(parent=self.weekTab)
        self.generatePlotButton.setGeometry(QtCore.QRect(660, 680, 141, 61))
        self.generatePlotButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.generatePlotButton.setObjectName("generatePlotButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.weekTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 200, 411, 412))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.weekSumaryGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.weekSumaryGrid.setContentsMargins(0, 0, 0, 0)
        self.weekSumaryGrid.setSpacing(10)
        self.weekSumaryGrid.setObjectName("weekSumaryGrid")
        self.wednesdayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.wednesdayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.wednesdayLine.setReadOnly(True)
        self.wednesdayLine.setObjectName("wednesdayLine")
        self.wednesdayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.wednesdayLine, 2, 1, 1, 1)
        self.mondayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.mondayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mondayLine.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.mondayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mondayLine.setReadOnly(True)
        self.mondayLine.setObjectName("mondayLine")
        self.weekSumaryGrid.addWidget(self.mondayLine, 0, 1, 1, 1)
        self.thursdayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.thursdayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.thursdayLine.setReadOnly(True)
        self.thursdayLine.setObjectName("thursdayLine")
        self.thursdayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.thursdayLine, 3, 1, 1, 1)
        self.tuesdayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.tuesdayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tuesdayLine.setReadOnly(True)
        self.tuesdayLine.setObjectName("tuesdayLine")
        self.tuesdayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.tuesdayLine, 1, 1, 1, 1)
        self.fridayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.fridayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fridayLine.setReadOnly(True)
        self.fridayLine.setObjectName("fridayLine")
        self.fridayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.fridayLine, 4, 1, 1, 1)
        self.tuesdayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tuesdayLabel.setFont(font)
        self.tuesdayLabel.setObjectName("tuesdayLabel")
        self.weekSumaryGrid.addWidget(self.tuesdayLabel, 1, 0, 1, 1)
        self.wednesdayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.wednesdayLabel.setFont(font)
        self.wednesdayLabel.setObjectName("wednesdayLabel")
        self.weekSumaryGrid.addWidget(self.wednesdayLabel, 2, 0, 1, 1)
        self.saturdayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.saturdayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saturdayLine.setReadOnly(True)
        self.saturdayLine.setObjectName("saturdayLine")
        self.saturdayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.saturdayLine, 5, 1, 1, 1)
        self.thursdayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.thursdayLabel.setFont(font)
        self.thursdayLabel.setObjectName("thursdayLabel")
        self.weekSumaryGrid.addWidget(self.thursdayLabel, 3, 0, 1, 1)
        self.sundayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.sundayLabel.setBaseSize(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sundayLabel.setFont(font)
        self.sundayLabel.setObjectName("sundayLabel")
        self.weekSumaryGrid.addWidget(self.sundayLabel, 6, 0, 1, 1)
        self.fridayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fridayLabel.setFont(font)
        self.fridayLabel.setObjectName("fridayLabel")
        self.weekSumaryGrid.addWidget(self.fridayLabel, 4, 0, 1, 1)
        self.saturdayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.saturdayLabel.setFont(font)
        self.saturdayLabel.setObjectName("saturdayLabel")
        self.weekSumaryGrid.addWidget(self.saturdayLabel, 5, 0, 1, 1)
        self.sundayLine = QtWidgets.QLineEdit(parent=self.gridLayoutWidget_2)
        self.sundayLine.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sundayLine.setReadOnly(True)
        self.sundayLine.setObjectName("sundayLine")
        self.sundayLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weekSumaryGrid.addWidget(self.sundayLine, 6, 1, 1, 1)
        self.mondayLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mondayLabel.setFont(font)
        self.mondayLabel.setObjectName("mondayLabel")
        self.weekSumaryGrid.addWidget(self.mondayLabel, 0, 0, 1, 1)
        self.weekSumaryGrid.setRowMinimumHeight(0, 50)
        self.weekSumaryGrid.setRowMinimumHeight(1, 50)
        self.weekSumaryGrid.setRowMinimumHeight(2, 50)
        self.weekSumaryGrid.setRowMinimumHeight(3, 50)
        self.weekSumaryGrid.setRowMinimumHeight(4, 50)
        self.weekSumaryGrid.setRowMinimumHeight(5, 50)
        self.weekSumaryGrid.setRowMinimumHeight(6, 50)
        self.leftButton = QtWidgets.QPushButton(parent=self.weekTab)
        self.leftButton.setGeometry(QtCore.QRect(250, 100, 31, 31))
        self.leftButton.setText("<-")
        self.leftButton.setCheckable(True)
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(parent=self.weekTab)
        self.rightButton.setGeometry(QtCore.QRect(600, 100, 31, 31))
        self.rightButton.setObjectName("rightButton")
        self.weekLineEdit = QtWidgets.QLineEdit(parent=self.weekTab)
        self.weekLineEdit.setGeometry(QtCore.QRect(410, 100, 31, 31))
        self.weekLineEdit.setReadOnly(False)
        self.weekLineEdit.setObjectName("weekLineEdit")
        self.weekLabel = QtWidgets.QLabel(parent=self.weekTab)
        self.weekLabel.setGeometry(QtCore.QRect(300, 100, 101, 31))
        self.weekLabel.setObjectName("weekLabel")
        self.yearLineEdit = QtWidgets.QLineEdit(parent=self.weekTab)
        self.yearLineEdit.setGeometry(QtCore.QRect(530, 100, 51, 31))
        self.yearLineEdit.setReadOnly(False)
        self.yearLineEdit.setObjectName("yearLineEdit")
        self.yearLabel = QtWidgets.QLabel(parent=self.weekTab)
        self.yearLabel.setGeometry(QtCore.QRect(480, 100, 31, 31))
        self.yearLabel.setObjectName("yearLabel")
        self.dateLineLabel = QtWidgets.QLineEdit(parent=self.weekTab)
        self.dateLineLabel.setGeometry(QtCore.QRect(330, 150, 81, 31))
        self.dateLineLabel.setReadOnly(True)
        self.dateLineLabel.setObjectName("dataLineLabel")
        self.dateLineLabel2 = QtWidgets.QLineEdit(parent=self.weekTab)
        self.dateLineLabel2.setGeometry(QtCore.QRect(470, 150, 81, 31))
        self.dateLineLabel2.setReadOnly(True)
        self.dateLineLabel2.setObjectName("dateLineLabel2")
        self.tabWidget.addTab(self.weekTab, "")
        self.dayTab = QtWidgets.QWidget()
        self.dayTab.setObjectName("dayTab")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.dayTab)
        self.dateEdit.setGeometry(QtCore.QRect(350, 10, 200, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.HighlightedText, brush)
        self.dateEdit.setPalette(palette)
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 30), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2023, 6, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.epicDayLabel = QtWidgets.QLabel(parent=self.dayTab)
        self.epicDayLabel.setGeometry(QtCore.QRect(270, 10, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.epicDayLabel.setFont(font)
        self.epicDayLabel.setObjectName("epicDayLabel")
        self.dayRecordsList = QtWidgets.QListWidget(parent=self.dayTab)
        self.dayRecordsList.setGeometry(QtCore.QRect(40, 70, 811, 581))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)

        self.dayRecordsList.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dayRecordsList.setFont(font)
        self.dayRecordsList.setObjectName("dayRecordsList")
        self.daySumSortLabel = QtWidgets.QLabel(parent=self.dayTab)
        self.daySumSortLabel.setGeometry(QtCore.QRect(600, 20, 81, 31))
        self.daySumSortLabel.setObjectName("daySumSortLabel")
        self.daySumSortComboBox = QtWidgets.QComboBox(parent=self.dayTab)
        self.daySumSortComboBox.setGeometry(QtCore.QRect(690, 20, 121, 31))
        self.daySumSortComboBox.setObjectName("daySumSortComboBox")
        self.daySumSortComboBox.addItem("")
        self.daySumSortComboBox.addItem("")
        self.daySumSortComboBox.addItem("")
        self.daySumSortComboBox.addItem("")
        self.tabWidget.addTab(self.dayTab, "")
        self.AllPaymentsTab = QtWidgets.QWidget()
        self.AllPaymentsTab.setObjectName("AllPaymentsTab")
        self.allPaymentsList = QtWidgets.QListWidget(parent=self.AllPaymentsTab)
        self.allPaymentsList.setGeometry(QtCore.QRect(40, 70, 811, 591))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.allPaymentsList.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.allPaymentsList.setFont(font)
        self.allPaymentsList.setTextElideMode(QtCore.Qt.TextElideMode.ElideMiddle)
        self.allPaymentsList.setModelColumn(0)
        self.allPaymentsList.setObjectName("allPaymentsList")
        self.editButton = QtWidgets.QPushButton(parent=self.AllPaymentsTab)
        self.editButton.setGeometry(QtCore.QRect(550, 680, 151, 61))
        self.editButton.setObjectName("editButton")
        self.addButton = QtWidgets.QPushButton(parent=self.AllPaymentsTab)
        self.addButton.setGeometry(QtCore.QRect(190, 680, 151, 61))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.AllPaymentsTab)
        self.deleteButton.setGeometry(QtCore.QRect(370, 680, 151, 61))
        self.deleteButton.setObjectName("deleteButton")
        self.allPaymentsSortLabel = QtWidgets.QLabel(parent=self.AllPaymentsTab)
        self.allPaymentsSortLabel.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.allPaymentsSortLabel.setObjectName("allPaymentsSortLabel")
        self.allPaymentsSortCombo = QtWidgets.QComboBox(parent=self.AllPaymentsTab)
        self.allPaymentsSortCombo.setGeometry(QtCore.QRect(160, 20, 121, 31))
        self.allPaymentsSortCombo.setObjectName("allPaymentsSortCombo")
        self.allPaymentsSortCombo.addItem("")
        self.allPaymentsSortCombo.addItem("")
        self.allPaymentsSortCombo.addItem("")
        self.allPaymentsSortCombo.addItem("")
        self.allPaymentsSortCombo.addItem("")
        self.tabWidget.addTab(self.AllPaymentsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 896, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWczytaj = QtGui.QAction(parent=MainWindow)
        self.actionWczytaj.setObjectName("actionWczytaj")
        self.actionZapisz = QtGui.QAction(parent=MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionWyjdz = QtGui.QAction(parent=MainWindow)
        self.actionWyjdz.setObjectName("actionWyjdz")
        self.menuFile.addAction(self.actionWczytaj)
        self.menuFile.addAction(self.actionZapisz)
        self.menuFile.addAction(self.actionWyjdz)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CalendarTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>asdasd</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CalendarTab), _translate("MainWindow", "Kalendarz"))
        self.epicLabel.setText(_translate("MainWindow", "Podsumowanie tygodnia"))
        self.generatePlotButton.setText(_translate("MainWindow", "Wygeneruj wykres"))
        self.tuesdayLabel.setText(_translate("MainWindow", "Wtorek"))
        self.wednesdayLabel.setText(_translate("MainWindow", "Środa"))
        self.thursdayLabel.setText(_translate("MainWindow", "Czwartek"))
        self.sundayLabel.setText(_translate("MainWindow", "Niedziela"))
        self.fridayLabel.setText(_translate("MainWindow", "Piątek"))
        self.saturdayLabel.setText(_translate("MainWindow", "Sobota"))
        self.mondayLabel.setText(_translate("MainWindow", "Poniedziałek"))
        self.rightButton.setText(_translate("MainWindow", "->"))
        self.weekLabel.setText(_translate("MainWindow", "Nr. Tygodnia"))
        self.yearLabel.setText(_translate("MainWindow", "Rok"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weekTab), _translate("MainWindow", "Podsumowanie tygodnia"))
        self.epicDayLabel.setText(_translate("MainWindow", "Dzień"))
        self.daySumSortLabel.setText(_translate("MainWindow", "Sortuj po"))
        self.daySumSortComboBox.setItemText(0, _translate("MainWindow", "Brak"))
        self.daySumSortComboBox.setItemText(1, _translate("MainWindow", "Po nazwie"))
        self.daySumSortComboBox.setItemText(2, _translate("MainWindow", "Po kategorii"))
        self.daySumSortComboBox.setItemText(3, _translate("MainWindow", "Po koszcie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dayTab), _translate("MainWindow", "Podsumowanie dnia"))
        self.editButton.setText(_translate("MainWindow", "Edytuj płatność"))
        self.addButton.setText(_translate("MainWindow", "Dodaj Płatność"))
        self.deleteButton.setText(_translate("MainWindow", "Usuń Płatność"))
        self.allPaymentsSortLabel.setText(_translate("MainWindow", "Sortuj po"))
        self.allPaymentsSortCombo.setItemText(0, _translate("MainWindow", "Brak"))
        self.allPaymentsSortCombo.setItemText(1, _translate("MainWindow", "Po nazwie"))
        self.allPaymentsSortCombo.setItemText(2, _translate("MainWindow", "Po dacie"))
        self.allPaymentsSortCombo.setItemText(3, _translate("MainWindow", "Po kategorii"))
        self.allPaymentsSortCombo.setItemText(4, _translate("MainWindow", "Po koszcie"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AllPaymentsTab), _translate("MainWindow", "Wszystkie płatności"))
        self.menuFile.setTitle(_translate("MainWindow", "Plik"))
        self.actionWczytaj.setText(_translate("MainWindow", "Wczytaj"))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz"))
        self.actionWyjdz.setText(_translate("MainWindow", "Wyjdź"))

    def setAllTriggersAndSignals(self):
        self.menuBarSetup()
        self.calendarTabSetup()
        self.weekSummarySetup()
        self.daySummarySetup()
        self.allPaymentsSetup()

    def menuBarSetup(self):
        self.actionWczytaj.triggered.connect(lambda: am.loadAction(self.appLogicInstance, self.allPaymentsList))
        self.actionZapisz.triggered.connect(lambda: am.saveAction(self.appLogicInstance))
        self.actionWyjdz.triggered.connect(QtWidgets.QMainWindow.close)

    def calendarTabSetup(self):
        self.calendar.selectionChanged.connect(lambda: cm.calendarTabUpdate(self))
        self.calendarRecordsList.itemDoubleClicked.connect(lambda: addDialog.runReadOnly(MainWindow, self.appLogicInstance.getCalendarEntryList(), self.calendarRecordsList))

    def daySummarySetup(self):
        self.dayRecordsList.itemDoubleClicked.connect(lambda: addDialog.runReadOnly(MainWindow, self.appLogicInstance.getDaySummaryEntryList(), self.dayRecordsList))
        self.dateEdit.dateChanged.connect(lambda: dsm.dateEditDateChanged(self.dateEdit, self.appLogicInstance, self.dayRecordsList, self.daySumSortComboBox))
        self.daySumSortComboBox.currentIndexChanged.connect(lambda: dsm.daySummarySortComboBoxChanged(self.daySumSortComboBox, self.appLogicInstance, self.dayRecordsList))

    def weekSummarySetup(self):
        wm.updateWeekTab(self)
        listOfQEditLines = [self.mondayLine, self.tuesdayLine, self.wednesdayLine, self.thursdayLine, self.fridayLine, self.saturdayLine, self.sundayLine, self.dateLineLabel, self.dateLineLabel2, self.weekLineEdit, self.yearLineEdit]
        self.leftButton.clicked.connect(lambda: wm.leftButtonAction(listOfQEditLines, self.appLogicInstance))
        self.rightButton.clicked.connect(lambda: wm.rightButtonAction(listOfQEditLines, self.appLogicInstance))
    def allPaymentsSetup(self):
        self.allPaymentsList.itemDoubleClicked.connect(lambda: addDialog.runReadOnly(MainWindow, self.appLogicInstance.getAllPaymentsEntryList(), self.allPaymentsList))
        self.allPaymentsSortCombo.currentIndexChanged.connect(lambda: apm.allPaymentsSortComboBoxChanged(self.allPaymentsSortCombo, self.appLogicInstance, self.allPaymentsList))
        self.addButton.clicked.connect(lambda: apm.addItem(self.appLogicInstance, self.allPaymentsList, MainWindow, self))
        self.deleteButton.clicked.connect(lambda: apm.deleteItem(self))
        self.editButton.clicked.connect(lambda: apm.editItem(MainWindow, self))

    def updateAllTabs(self):
        cm.calendarTabUpdate(ui)
        wm.updateWeekTab(ui)
        apm.allPaymentsTabUpdate(ui)
        dsm.daySummaryTabUpdate(ui)


if __name__ == "__main__":
    import sys

    sys._excepthook = sys.excepthook
    def exception_hook(exctype, value, traceback):
        print(exctype, value, traceback)
        sys._excepthook(exctype, value, traceback)
        sys.exit(1)
    sys.excepthook = exception_hook
    app = QtWidgets.QApplication(sys.argv)
    qdarktheme.setup_theme()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setAllTriggersAndSignals()
    MainWindow.show()
    traceback.print_exc()
    sys.exit(app.exec())

